# Generated by Django 5.1 on 2024-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('best_selling', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='description')),
            ],
        ),
    ]
